#!/bin/sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep '^Volume: ' | awk '{ print $2 }')"
split() {
  IFS=$2
  set -- $1
  printf '%s' "$@"
}

volume="$(printf "%.0f" "$(split "$vol" ".")")"

icon=" "

echo "$icon$volume%"

[ -z "$BLO" ] || (pkill -SIGRTMIN+${BLO} -x dwmblocks)
