#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$capacity" -eq 100 ]; then
  notify-send -u low -i "󰁹" "FULL BATTERY" "Your battery is now at 100%"
elif [ "$capacity" -eq 40 ]; then
  notify-send -u low -i "󰁽" "LOW BATTERY" "Your battery is at 40%"
elif [ "$capacity" -eq 20 ]; then
  notify-send -u normal -i "󰁻" "LOW BATTERY" "Your battery is at 20%"
elif [ "$capacity" -eq 15 ]; then
  notify-send -u critical -i "󰁻" "LOW BATTERY" "Your battery is at 15%. Please plug it in."
fi 
