#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n󰍃  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/styles/main.rasi"')

case "$chosen" in
	"  Power Off") sudo poweroff ;;
	"  Restart") sudo reboot ;;
	"󰍃  Log Out") pkill -KILL -u $USER ;;
	"  Lock") slock ;;
	*) exit 1 ;;
esac
